imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    translator:
        enabled: true
        fallbacks: ['%locale%']
        logging: true
        paths:
            - '%kernel.root_dir%/Resources/translations'
            - '%kernel.root_dir%/Resources/translations/Back'
            - '%kernel.root_dir%/Resources/translations/Front'
            - '%kernel.root_dir%/Resources/translations/Global'
            - '%kernel.root_dir%/Resources/translations/Emails'
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection:
        enabled: true
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.pdo
        cookie_lifetime: 0
    fragments:       ~
    http_method_override: true

services:
    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - { db_table: app_sessions, db_username: '%database_user%', db_password: '%database_password%' }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
       strime_facebook_app_id: %strime_facebook_app_id%
       strime_video_default_accepted_extensions: %strime_video_default_accepted_extensions%
       strime_image_default_accepted_extensions: %strime_image_default_accepted_extensions%
       strime_audio_default_accepted_extensions: %strime_audio_default_accepted_extensions%
       video_default_gold_number: %strime_video_gold_number%
       video_default_width: %strime_video_default_width%
       video_default_height: %strime_video_default_height%
       video_default_volume: %strime_video_volume%
       image_default_width: %strime_video_default_width%
       image_default_height: %strime_video_default_height%


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
    bundles:        [ StrimeGlobalBundle, StrimeBackBundle, StrimeFrontBundle, StrimeAdminBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/bin/uglifyjs
    assets:
        jquery_and_bootstrap:
            inputs:
                - '@StrimeFrontBundle/Resources/public/js/jquery-2.1.4.min.js'
                - '@StrimeFrontBundle/Resources/public/js/bootstrap.min.js'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    logging: false

# Cookie bar
xsolve_cookie_acknowledgement:
    # response_injection: true # default true
    # 60 * 60 * 24 * 7
    cookie_expiry_time: 604800
    template: cookie-bar.html.twig # twig template name, default: XsolveCookieAcknowledgementBundle::cookie_acknowledgement_bar.html.twig

# Liip Image Manager Configuration
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../web"
                cache_prefix: "media/cache"

    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.root_dir%/../"
                    - "%kernel.root_dir%/../web/"
                    - "%kernel.root_dir%/../web/uploads"
                    - "%kernel.root_dir%/../web/uploads/avatars"

    filter_sets:
        cache: ~
        profile_pic_menu:
            quality: 75
            filters:
                thumbnail: { size: [40, 40], mode: outbound }
        profile_pic:
            quality: 75
            filters:
                thumbnail: { size: [80, 80], mode: outbound }

# Configure the logs with Monolog
monolog:
    handlers:
        main:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
            # max number of log files to keep
            # defaults to zero, which means infinite files
            max_files: 10
        console:
            type:  console

# Nelmio CORS configuration
nelmio_cors:
    paths:
        '^/':
            allow_origin: ['^https://encoding.company.com', '^https://encoding1.company.com', '^https://encoding2.company.com']
            allow_headers: ['Authorization', 'X-Requested-With', 'Content-Type', 'Accept', 'Origin', 'X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
