imports:
    - { resource: config.yml }

framework:
    test: ~
    router:
        resource: "%kernel.root_dir%/config/routing_test.yml"
        strict_requirements: ~
    profiler: { only_exceptions: false }
    session:
        cookie_lifetime: 0

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: support@company.com
            to_email:   your@email.com
            subject:    A critical error occured
            level:      warning
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    debug: %kernel.debug%
    use_controller: true
    filters:
        uglifyjs2:
            bin: /usr/bin/uglifyjs
        cssrewrite: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    logging: true

# KNP Snappy Bundle
# Deals with PDF generation
knp_snappy:
    pdf:
        enabled: true
        binary: /usr/bin/wkhtmltopdf.sh
        options: []

# Nelmio CORS configuration
nelmio_cors:
    paths:
        '^/':
            allow_origin: ['^https://encoding.company.com', '^https://encoding1.company.com', '^https://encoding2.company.com']
            allow_headers: ['Authorization', 'X-Requested-With', 'Content-Type', 'Accept', 'Origin', 'X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
