# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    strime.invoice:
        class: Strime\GlobalBundle\Invoice\Invoice
        arguments: ['@knp_snappy.pdf','@templating']
    strime.invoice.admin_helper:
        class: Strime\GlobalBundle\Invoice\AdminHelper
        arguments: ['@service_container']
    strime.back_helpers.form:
        class: Strime\BackBundle\Helpers\Form
        arguments: ['@service_container']
    strime.back_helpers.users:
        class: Strime\BackBundle\Helpers\Users
        arguments: ['@service_container']
    strime.back_helpers.contacts:
        class: Strime\BackBundle\Helpers\Contacts
        arguments: ['@service_container']
    strime.helpers.form:
        class: Strime\GlobalBundle\Helpers\Form
        arguments: ['@service_container']
    strime.helpers.signup:
        class: Strime\GlobalBundle\Helpers\Signup
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    strime.sitemap:
        class: Strime\GlobalBundle\Helpers\Sitemap
        arguments: ['@router', '@doctrine.orm.entity_manager', '@service_container']
    app.tokens.action_listener:
        class: Strime\GlobalBundle\EventListener\TokenListener
        arguments: [ '@service_container' ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    app.tokens.exception_listener:
        class: Strime\GlobalBundle\EventListener\ExceptionListener
        arguments: [ '@service_container' ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    app.locale_listener:
        class: Strime\GlobalBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
